const{Client,GatewayIntentBits,Partials,PermissionsBitField,AuditLogEvent,EmbedBuilder,Collection}=require("discord.js");
const token=process.env.BOT_TOKEN,id=process.env.CLIENT_ID;if(!token)process.exit(1);
const CONFIG={LOG_CHANNEL_ID:process.env.LOG_CHANNEL_ID||"",OWNER_ID:process.env.OWNER_ID||"",WHITELIST:(process.env.WHITELIST||"").split(",").filter(Boolean),RAID:{enabled:true,joinLimit:5,timeWindow:10000},SPAM:{enabled:true,messageLimit:6,timeWindow:5000,muteDuration:600000},BOT_PROTECTION:true};
if(CONFIG.OWNER_ID&&!CONFIG.WHITELIST.includes(CONFIG.OWNER_ID))CONFIG.WHITELIST.push(CONFIG.OWNER_ID);
const client=new Client({intents:[GatewayIntentBits.Guilds,GatewayIntentBits.GuildMembers,GatewayIntentBits.GuildMessages,GatewayIntentBits.MessageContent,GatewayIntentBits.GuildModeration],partials:[Partials.Channel,Partials.GuildMember,Partials.Message]});
const spam=new Collection(),joins=[];
function white(x){return CONFIG.WHITELIST.includes(x)}
async function log(g,t,d,c=0x3b82f6){try{const ch=CONFIG.LOG_CHANNEL_ID&&g.channels.cache.get(CONFIG.LOG_CHANNEL_ID);if(!ch)return;await ch.send({embeds:[new EmbedBuilder().setColor(c).setTitle(t).setDescription(d).setTimestamp()]})}catch{}}
async function exec(g,type,target){try{const l=await g.fetchAuditLogs({type,limit:10});return l.entries.find(e=>e.target?.id===target&&Date.now()-e.createdTimestamp<10000)?.executor||null}catch{return null}}
async function punish(g,id,reason){if(!id||white(id))return;const m=await g.members.fetch(id).catch(()=>null);if(!m)return;if(m.permissions.has(PermissionsBitField.Flags.Administrator)){await log(g,"⚠️ محاولة تخريب",`<@${id}> — ${reason}\nAdministrator: لم يتم طرده`,0xf59e0b);return}await m.kick(reason).catch(async()=>await m.timeout(86400000,reason).catch(()=>{}));await log(g,"🛡️ إجراء أمني",`<@${id}> — **${reason}**`,0xef4444)}
client.once("ready",()=>{console.log(`Protection online: ${client.user.tag}`);client.user.setPresence({activities:[{name:"Protection System",type:3}],status:"online"})});
client.on("guildMemberAdd",async m=>{if(m.user.bot){const x=await exec(m.guild,AuditLogEvent.BotAdd,m.id);if(CONFIG.BOT_PROTECTION&&x&&!white(x.id)){await m.kick("Unauthorized Bot").catch(()=>{});await punish(m.guild,x.id,`إضافة بوت: ${m.user.tag}`)}return}if(!CONFIG.RAID.enabled)return;const n=Date.now();joins.push(n);while(joins.length&&n-joins[0]>CONFIG.RAID.timeWindow)joins.shift();if(joins.length>=CONFIG.RAID.joinLimit){await log(m.guild,"🚨 Anti-Raid",`تم اكتشاف ${joins.length} أعضاء خلال وقت قصير`,0xef4444);await m.guild.setVerificationLevel(4,"Protection Anti-Raid").catch(()=>{});setTimeout(()=>m.guild.setVerificationLevel(1,"Protection Anti-Raid Ended").catch(()=>{}),60000)}});
client.on("messageCreate",async m=>{if(!CONFIG.SPAM.enabled||!m.guild||m.author.bot||white(m.author.id))return;const n=Date.now(),a=[...(spam.get(m.author.id)||[]),n].filter(t=>n-t<=CONFIG.SPAM.timeWindow);spam.set(m.author.id,a);if(a.length>=CONFIG.SPAM.messageLimit){spam.delete(m.author.id);await m.delete().catch(()=>{});await m.member?.timeout(CONFIG.SPAM.muteDuration,"Protection Anti-Spam").catch(()=>{});await log(m.guild,"🚫 Anti-Spam",`<@${m.author.id}>`,0xef4444)}});
async function audit(ch,type,reason){const x=await exec(ch.guild,type,ch.id);if(x&&!white(x.id))await punish(ch.guild,x.id,reason)}
client.on("channelDelete",c=>audit(c,AuditLogEvent.ChannelDelete,`حذف روم: ${c.name}`));
client.on("roleDelete",r=>audit(r,AuditLogEvent.RoleDelete,`حذف رتبة: ${r.name}`));
client.on("guildUpdate",async(o,n)=>{const x=await exec(n,AuditLogEvent.GuildUpdate,n.id);if(!x||white(x.id))return;const a=[];if(o.name!==n.name)a.push("تغيير الاسم");if(o.icon!==n.icon)a.push("تغيير الصورة");if(a.length){await punish(n,x.id,a.join(" + "));await log(n,"🛡️ Server Protection",`<@${x.id}> — ${a.join("\n")}`,0xef4444)}});
process.on("unhandledRejection",console.error);process.on("uncaughtException",console.error);
client.login(token).catch(e=>{console.error("Discord login failed:",e.message);process.exit(1)});
